// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace StyleCssNamespace {
  export interface IStyleCss {
    active: string;
    item: string;
    unavailable: string;
    wrapper: string;
  }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: StyleCssNamespace.IStyleCss;
};

export = StyleCssModule;
