// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace StyleCssNamespace {
  export interface IStyleCss {
    chartContainer: string;
    intervalItem: string;
    intervals: string;
    marketName: string;
    showOrders: string;
  }
}

declare const StyleCssModule: StyleCssNamespace.IStyleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: StyleCssNamespace.IStyleCss;
};

export = StyleCssModule;
