name: Test and deploy dev

on:
  push:
    branches:
      - dev

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm ci

      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm test

      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          rm -rf dist-dev
          DIST_ENV=development npx deploy-to-git --repository https://${GITHUB_TOKEN}@github.com/Altamoon/altamoon-web-dev.git --folder dist-dev --script "npm run build:browser"
